[package]
name = "lambdaworks-stark"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
lambdaworks-math = { git = "https://github.com/lambdaclass/lambdaworks", version = "0.1.1" }
lambdaworks-crypto = { git = "https://github.com/lambdaclass/lambdaworks", version = "0.1.1" }
thiserror = "1.0.38"
log = "0.4.17"
bincode = { version = "2.0.0-rc.2", tag = "v2.0.0-rc.2", git = "https://github.com/bincode-org/bincode.git" }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-rs/" }
sha3 = "0.10.6"
num-integer = "0.1.45"
proptest = "1.2.0"

[dev-dependencies]
hex = "0.4.3"
criterion = "0.4"
env_logger = "*"
test-log = { version = "0.2.11", features = ["log"] }
assert_matches = "1.5.0"
rstest = "0.17.0"

[features]
test_fiat_shamir = []
instruments = [] # This enables timing prints in prover and verifier
metal = ["lambdaworks-math/metal"]

[[bench]]
name = "criterion_starks"
harness = false
metal = ["lambdaworks-math/metal"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[profile.test]
lto = "thin"
opt-level = 3
debug = 2
