[package]
name = "lambdaworks-stark"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
lambdaworks-math = { git = "https://github.com/lambdaclass/lambdaworks", rev = "943963c" }
lambdaworks-crypto = { git = "https://github.com/lambdaclass/lambdaworks", rev = "943963c" }
lambdaworks-fft = { git = "https://github.com/lambdaclass/lambdaworks", rev = "943963c" }
thiserror = "1.0.38"
log = "0.4.17"
bincode = { version = "2.0.0-rc.2", tag = "v2.0.0-rc.2", git = "https://github.com/bincode-org/bincode.git" }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-rs/" }

[dev-dependencies]
hex = "0.4.3"
criterion = "0.4"
env_logger = "*"
test-log = { version = "0.2.11", features = ["log"] }
assert_matches = "1.5.0"
rstest = "0.17.0"

[features]
test_fiat_shamir = []
metal = ["lambdaworks-fft/metal"]
cuda = ["lambdaworks-fft/cuda"]
