[book]
authors = ["Javier Chatruc", "Est√©fano Bargas", "Sergio Chouhy", "Agustin Garassino"]
language = "en"
multilingual = false
src = "src"
title = "docs"

[preprocessor.katex]

[output.html]
mathjax-support = true
